// Comics Data
const comicsData = [
    {
        id: 1,
        title: "The Amazing Spider-Man",
        issue: "Issue #1",
        publisher: "Marvel",
        price: 5.99,
        genre: "Superhero",
        releaseDate: "2024-03-20",
        cover: "IMAGES_WEB/image copy 3.png",
        synopsis: "Peter Parker swings back into action with new challenges and classic villains in this fresh take on the web-slinger.",
        writer: "Zeb Wells",
        artist: "John Romita Jr.",
        badge: "NEW"
    },
    {
        id: 2,
        title: "Batman: The Court of Owls",
        issue: "Issue #1",
        publisher: "DC",
        price: 6.99,
        genre: "Superhero",
        releaseDate: "2024-03-18",
        cover: "IMAGES_WEB/image copy 6.png",
        synopsis: "Batman uncovers a secret society that has controlled Gotham for centuries in this modern classic.",
        writer: "Scott Snyder",
        artist: "Greg Capullo",
        badge: "POPULAR"
    },
    {
        id: 13,
        title: "The Walking Dead",
        issue: "Compendium 1",
        publisher: "Image",
        price: 34.99,
        genre: "Horror",
        releaseDate: "2024-03-20",
        cover: "IMAGES_WEB/walkingdead.jpg",
        synopsis: "Rick Grimes wakes from a coma to find the world overrun by zombies in this survival epic.",
        writer: "Robert Kirkman",
        artist: "Charlie Adlard",
        badge: "POPULAR"
    },
    {
        id: 20,
        title: "Teenage Mutant Ninja Turtles",
        issue: "The Last Ronin",
        publisher: "IDW",
        price: 7.99,
        genre: "Action",
        releaseDate: "2024-04-08",
        cover: "IMAGES_WEB/image copy 4.png",
        synopsis: "In a future NYC, the last surviving Turtle seeks vengeance for his fallen family.",
        writer: "Kevin Eastman",
        artist: "Ben Bishop",
        badge: "NEW"
    },
    {
        id: 15,
        title: "Ms. Marvel",
        issue: "Issue #1",
        publisher: "Marvel",
        price: 4.99,
        genre: "Superhero",
        releaseDate: "2024-03-25",
        cover: "IMAGES_WEB/image copy.png",
        synopsis: "Kamala Khan gains incredible shapeshifting abilities and becomes the new Ms. Marvel.",
        writer: "G. Willow Wilson",
        artist: "Adrian Alphona",
        badge: "NEW"
    },
    {
        id: 14,
        title: "Watchmen",
        issue: "Issue #1",
        publisher: "DC",
        price: 7.99,
        genre: "Superhero",
        releaseDate: "2024-03-18",
        cover: "IMAGES_WEB/WATCHMEN_DC.jpg",
        synopsis: "A murder mystery that unravels a plot with catastrophic consequences for the world.",
        writer: "Alan Moore",
        artist: "Dave Gibbons",
        badge: "CLASSIC"
    },
    {
        id: 16,
        title: "Hellboy",
        issue: "Seed of Destruction",
        publisher: "Dark Horse",
        price: 6.99,
        genre: "Horror",
        releaseDate: "2024-03-22",
        cover: "IMAGES_WEB/hellboi.jpg",
        synopsis: "A demon raised to be a hero fights supernatural threats while grappling with his destiny.",
        writer: "Mike Mignola",
        artist: "John Byrne",
        badge: "POPULAR"
    },
    {
        id: 17,
        title: "Spawn",
        issue: "Issue #1",
        publisher: "Image",
        price: 5.99,
        genre: "Superhero",
        releaseDate: "2024-03-28",
        cover: "IMAGES_WEB/hellos.jpg",
        synopsis: "A murdered CIA agent returns from hell as a demonic creature seeking revenge.",
        writer: "Todd McFarlane",
        artist: "Todd McFarlane",
        badge: "CLASSIC"
    },
    {
        id: 18,
        title: "Black Panther",
        issue: "A Nation Under Our Feet",
        publisher: "Marvel",
        price: 6.49,
        genre: "Superhero",
        releaseDate: "2024-04-01",
        cover: "IMAGES_WEB/black_panther.jpg",
        synopsis: "T'Challa faces a violent uprising in Wakanda that threatens to tear the nation apart.",
        writer: "Ta-Nehisi Coates",
        artist: "Brian Stelfreeze",
        badge: "POPULAR"
    },
    {
        id: 22,
        title: "My Hero Academia",
        issue: "Volume 1",
        publisher: "Viz Media",
        price: 9.99,
        genre: "Superhero",
        releaseDate: "2024-04-15",
        cover: "IMAGES_WEB/My_HERO_ACADEMIA.jpg",
        synopsis: "In a world where 80% of the population has superpowers, a quirkless boy dreams of becoming a hero and gets his chance from the world's greatest hero.",
        writer: "Kohei Horikoshi",
        artist: "Kohei Horikoshi",
        badge: "POPULAR"
    },
    {
        id: 23,
        title: "Attack on Titan",
        issue: "Volume 1",
        publisher: "Kodansha",
        price: 10.99,
        genre: "Action",
        releaseDate: "2024-04-18",
        cover: "IMAGES_WEB/Attack_on_titan.jpg",
        synopsis: "Humanity lives in fear of gigantic Titans that devour humans, until Eren Yeager vows to eradicate them after his home is destroyed.",
        writer: "Hajime Isayama",
        artist: "Hajime Isayama",
        badge: "POPULAR"
    },
    {
        id: 19,
        title: "The Sandman",
        issue: "Preludes & Nocturnes",
        publisher: "Vertigo",
        price: 8.99,
        genre: "Fantasy",
        releaseDate: "2024-04-05",
        cover: "IMAGES_WEB/NEIL.jpg",
        synopsis: "The Lord of Dreams escapes captivity and sets out to restore his kingdom.",
        writer: "Neil Gaiman",
        artist: "Sam Kieth",
        badge: "AWARD WINNING"
    },
];